require "./records"

module Kafka::Protocol::Structure
  class LegacyRecord
    # The current offset and size for all the fixed-length fields
    CRC_OFFSET = 0
    CRC_LENGTH = 4
    MAGIC_OFFSET = CRC_OFFSET + CRC_LENGTH
    MAGIC_LENGTH = 1
    ATTRIBUTES_OFFSET = MAGIC_OFFSET + MAGIC_LENGTH
    ATTRIBUTES_LENGTH = 1
    TIMESTAMP_OFFSET = ATTRIBUTES_OFFSET + ATTRIBUTES_LENGTH
    TIMESTAMP_LENGTH = 8
    KEY_SIZE_OFFSET_V0 = ATTRIBUTES_OFFSET + ATTRIBUTES_LENGTH
    KEY_SIZE_OFFSET_V1 = TIMESTAMP_OFFSET + TIMESTAMP_LENGTH
    KEY_SIZE_LENGTH = 4
    KEY_OFFSET_V0 = KEY_SIZE_OFFSET_V0 + KEY_SIZE_LENGTH
    KEY_OFFSET_V1 = KEY_SIZE_OFFSET_V1 + KEY_SIZE_LENGTH
    VALUE_SIZE_LENGTH = 4

    # The size for the record header
    HEADER_SIZE_V0 = CRC_LENGTH + MAGIC_LENGTH + ATTRIBUTES_LENGTH
    HEADER_SIZE_V1 = CRC_LENGTH + MAGIC_LENGTH + ATTRIBUTES_LENGTH + TIMESTAMP_LENGTH
    
    # The amount of overhead bytes in a record
    RECORD_OVERHEAD_V0 = HEADER_SIZE_V0 + KEY_SIZE_LENGTH + VALUE_SIZE_LENGTH
  end
end
